# Site settings
title: Ryan of Libraria
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://remerjohnson.github.io" # the base hostname & protocol for your site
twitter_username: ejones82
github_username: remerjohnson
safe: true
lsi: false
source: .
timezone: America/Los_Angeles
encoding: utf-8

# Build settings
markdown: kramdown
